language: node_js
node_js:
  - '8'
before_install:
  - if [ ! -z "$ARTIFACTS_BUCKET" ] && [ ! -z "ARTIFACTS_KEY" ] && [ ! -z "ARTIFACTS_SECRET" ] ; then export UPLOAD_ARTIFACT=yes ; else echo artifact uploading is disabled; fi
install:
  - NODE_ENV=dev yarn install
  - if [ ! -z "$UPLOAD_ARTIFACT" ]; then curl -sL https://raw.githubusercontent.com/travis-ci/artifacts/master/install | bash; fi
script:
  - yarn test && CI=false yarn build
cache:
  yarn: true
  directories:
    - node_modules
after_success:
  - if [ ! -z "$UPLOAD_ARTIFACT" ] ; then artifacts upload --target-paths /${TRAVIS_REPO_SLUG}/${TRAVIS_BUILD_NUMBER}/NODE-${TRAVIS_NODE_VERSION} build/app.zip ; fi
  - if [ ! -z "$UPLOAD_ARTIFACT" ] && [ ! -z "$TRAVIS_PULL_REQUEST_SLUG" ] ; then echo "commenting on PRs is disabled ( npm run dpat -- travis pr-comment . --s3target /${TRAVIS_REPO_SLUG}/${TRAVIS_BUILD_NUMBER}/NODE-${TRAVIS_NODE_VERSION} )" ; fi
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: HjHdzHlj4W8bT0rpWlux5etA9t1wD/KstUWu+fziO/jxtMKDdjqkjuwZ7BTec+hCCptvNQqqxiyFWtkfViALEkJJ+QCeq5RlXdaXs+HJc3JD2DMNZmTIsWzWzGLDoA3gLjeEglWz0wl1pIovwSwWuY+ONwWu0TzmDouQkYR8MLtrlWJ5AW6tOow+9iA+js/UTl7wqpOOe7XjRSng0hwMCvWs0ir18R4FGLl7QvDIG+4A9dD9aeAeS+pMfXPmuy4C01w/ir8J8sy2pTeXY0KTlsIL6dVOp7x45Ro9YFMoeFbZf6VqyFBNSfTe2SIU0ELggCenP2s0lP3LiNV+jTDJHYD8RlunzO2LIGAH33VpuiVBDSzYamByokU0GqDzaFrF6KdCoWhapEzXblF5BF5ScmoivgrBOCO7POT1jVIp3Mi6HeNguswnIJmPWBHRuc3baZzr+2mLXH8nYuH2VqNvX5G2zznDJKgnFI0gZ3DM5UqfDZkH3pMs41OMlUJh0YQRZi64l82y99cmlp0iwqYYsLMvrXgFWlHb8OASwnGYC4KeENLHTz4dWb5gACZxrc14n85F0VKVbJPExMpFj6E29hwv63tJ4/FjMWkf3ybKkwJibUFjVmMjoQIn3Ve0097/RGKQzQraH7ILpUuixHm95fB2lfweZMwVkeNmPik/Eko=
  file: build/app.zip
  on:
    tags: true
